# Generated by Django 4.1.4 on 2023-01-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_current_bid_listing_last_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='last_bid',
            new_name='current_bid',
        ),
    ]
